Add -revoke to CA tool

diff --git a/CA/bin/mkssl-pem b/CA/bin/mkssl-pem
--- a/CA/bin/mkssl-pem
+++ b/CA/bin/mkssl-pem
@@ -8,20 +8,20 @@ BINDIR=${this:=.}
 LIBDIR=$(readlink -f "$BINDIR"/../lib)
 VARSFILE="$LIBDIR"/vars.sh
 
-if (( $# != 1 ))    # need the name
+if (( $# == 0  ))    # need the name
 then
     $0 -h >&2
     exit 1
 fi
 
-tmp=$(getopt -n $0 -o h -l help -- "$@")
+tmp=$(getopt -n $0 -o hr -l help,revoke -- "$@")
 eval set -- "$tmp"
 while true
 do
     o=$1; shift
     case "$o" in
     -h|--help)	cat <<-_HELP
-	$0 CN
+	$0 [-revoke] CN
 	    This creates a file "NAME-ssl.pem" containing the full bundle
 	    (CA, Cert, Key) for the client named NAME
 
@@ -29,6 +29,8 @@ do
                  or: $0 host2.domain.com
 _HELP
         exit 0 ;;
+    -r|--revoke)
+	mode=revoke;;
     --) break ;;
     esac
 done
@@ -57,42 +59,66 @@ test -d "$CA_DIR" || {
 
 _gitclean
 
-REQ_DIR=$CA_DIR/requests
-install -d -m 0700 "$REQ_DIR"
+if test "$mode" = revoke
+then
+    cn="$1"; shift
+    echo "revoking $cn"
+    read -sp 'password: ' pw
+    certs=$(grep "^V.*/CN=$cn$" $CA_DIR/index.txt \
+	|| { echo "$cn not found" >&2
+	  exit 1
+	})
+    <<<$certs tr -s '[[:space:]]' ' ' | cut -f3 -d' ' \
+    | {
+	while read serial; do
+	serials+=($serial)
+	pw=$pw openssl ca -passin env:pw -revoke $CA_DIR/newcerts/$serial.pem
+    done
+    test -f $CA_DIR/crlnumber || echo 00 > $CA_DIR/crlnumber
+    (
+	tmp=`mktemp`
+	trap 'rm -f $tmp' EXIT
+	pw=$pw openssl ca -passin env:pw -gencrl > $tmp
+	mv $tmp crl.pem
+    )
+    _git add crlnumber
+    _git add -u
+    _git commit -m "Revoke $cn (${serials[@]})"
+    }
+else
+    REQ_DIR=$CA_DIR/requests
+    install -d -m 0700 "$REQ_DIR"
 
-cn="$1"; shift
-test -d "$REQ_DIR/$cn" && {
-    echo "$0: $cn is already known. Aborting." >&2
-    exit 1
-}
+    cn="$1"; shift
 
-install -d -m 0700 "$REQ_DIR/$cn"
-openssl genrsa -out "$REQ_DIR/$cn/key.pem" 4096
-gitfiles+=("$REQ_DIR/$cn/key.pem")
+    install -d -m 0700 "$REQ_DIR/$cn"
+    openssl genrsa -out "$REQ_DIR/$cn/key.pem" 4096
+    gitfiles+=("$REQ_DIR/$cn/key.pem")
 
-openssl req -new -key "$REQ_DIR/$cn/key.pem" \
-	    -out "$REQ_DIR/$cn/csr.pem" \
-	    -subj "/C=$CA_DEFAULT_C/ST=$CA_DEFAULT_ST/L=$CA_DEFAULT_L/O=$CA_DEFAULT_O/OU=$CA_DEFAULT_OU/CN=$cn"
-gitfiles+=("$REQ_DIR/$cn/csr.pem")
+    openssl req -new -key "$REQ_DIR/$cn/key.pem" \
+		-out "$REQ_DIR/$cn/csr.pem" \
+		-subj "/C=$CA_DEFAULT_C/ST=$CA_DEFAULT_ST/L=$CA_DEFAULT_L/O=$CA_DEFAULT_O/OU=$CA_DEFAULT_OU/CN=$cn"
+    gitfiles+=("$REQ_DIR/$cn/csr.pem")
 
-install -d -m 0755 "$CA_DIR/certs"
-openssl ca -notext -out "$CA_DIR/certs/$cn.pem" -in "$REQ_DIR/$cn/csr.pem"
-gitfiles+=("$CA_DIR/certs/$cn.pem")
-gitfiles+=("$CA_DIR/newcerts")
+    install -d -m 0755 "$CA_DIR/certs"
+    openssl ca -notext -out "$CA_DIR/certs/$cn.pem" -in "$REQ_DIR/$cn/csr.pem"
+    gitfiles+=("$CA_DIR/certs/$cn.pem")
+    gitfiles+=("$CA_DIR/newcerts")
 
-# the rest looks spooky, but we didn't want to touch new files until we
-# got our data
-ssl=(
- "$(openssl x509 -in "$CA_DIR/certs/$cn.pem")"
- "$(openssl rsa  -in "$REQ_DIR/$cn/key.pem")"
- "$(openssl x509 -in "$CA_DIR/cacert.pem")"
-)
-IFS=$'\x0a'; echo "${ssl[*]}" | tee "$cn-ssl.pem" >"$REQ_DIR/$cn/ssl.pem"
-gitfiles+=("$REQ_DIR/$cn/ssl.pem")
+    # the rest looks spooky, but we didn't want to touch new files until we
+    # got our data
+    ssl=(
+	"$(openssl x509 -in "$CA_DIR/certs/$cn.pem")"
+	"$(openssl rsa  -in "$REQ_DIR/$cn/key.pem")"
+	"$(openssl x509 -in "$CA_DIR/cacert.pem")"
+    )
+    IFS=$'\x0a'; echo "${ssl[*]}" | tee "$cn-ssl.pem" >"$REQ_DIR/$cn/ssl.pem"
+    gitfiles+=("$REQ_DIR/$cn/ssl.pem")
 
-openssl x509 -in "$CA_DIR/certs/$cn.pem" >"$REQ_DIR/$cn/crt.pem"
-gitfiles+=("$REQ_DIR/$cn/crt.pem")
+    openssl x509 -in "$CA_DIR/certs/$cn.pem" >"$REQ_DIR/$cn/crt.pem"
+    gitfiles+=("$REQ_DIR/$cn/crt.pem")
 
-_git add "${gitfiles[@]}"
-_git add -u
-_git commit -m "New Cert for $cn"
+    _git add "${gitfiles[@]}"
+    _git add -u
+    _git commit -m "New Cert for $cn"
+fi
